apiVersion: v1
kind: Service
metadata:
  name: cloudsql-autoscaler
  namespace: cloudsql-autoscaler
  labels:
    app.kubernetes.io/name: cloudsql-autoscaler
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: cloudsql-autoscaler
    app.kubernetes.io/component: autoscaler

---
# Optional: ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudsql-autoscaler
  namespace: cloudsql-autoscaler
  labels:
    app.kubernetes.io/name: cloudsql-autoscaler
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudsql-autoscaler
      app.kubernetes.io/component: service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s